blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('post.urls', namespace='post'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', main, name = "main"),
    url(r'^create/$', create_post1, name="create_post1"),
    url(r'^create2/$', create_post2, name="create_post2"),
    url(r'^created/$', post_created, name="post_created"),
]

orm_test/models.py
from django.db import models

# Create your models here.
class country(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class person(models.Model):
    gender_type = (
        ('M', '남자'),
        ('F', '여자')
    )
    name = models.CharField(max_length=20)
    gender = models.CharField(choices=gender_type, max_length=2)
    age = models.PositiveIntegerField()
    country = models.ForeignKey(country)

    def __str__(self):
        return self.name

class relationship(models.Model):
    relationship_type = (
        ('1', '어사'),
        ('2', '친구'),
        ('3', '썸'),
        ('4', '연인')
    )
    person1 = models.ForeignKey(person, related_name='relationship1')
    person2 = models.ForeignKey(person, related_name='relationship2')
    type = models.CharField(choices = relationship_type, max_length=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('person1', 'person2', 'type')

    def __str__(self):
        return self.person1.name + "__"+self.person2.name + "__"+self.get_type_display()

class animal(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class pet(models.Model):
    name = models.CharField(max_length=20)
    animal = models.ForeignKey(animal)
    owner = models.ForeignKey(person)

    def __str__(self):
        return self.name

post/models.py
from django.db import models

# Create your models here.
class post(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=10)
    image = models.ImageField(upload_to='post/', null=True, blank=True)
    content = models.TextField(null=True)
    def __str__(self):
        return self.title + "__" +self.author

class comment(models.Model):
    post = models.ForeignKey(post, related_name="post_comment")
    content = models.CharField(max_length=200)

class supplier(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class plan(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class plan_group(models.Model):
    name = models.CharField(max_length=100)
    supplier = models.ForeignKey(supplier)

    def __str__(self):
        return self.name

class plan_plan_group_manage(models.Model):
    plan = models.ForeignKey(plan)
    plan_group = models.ForeignKey(plan_group)

    class Meta:
        unique_together = ('plan', 'plan_group__supplier')

    def __str__(self):
        return str(self.plan) + "__" +str(self.plan_group)

post/forms.py
from django import forms
from .models import *

class post_create_form(forms.ModelForm):
    class Meta:
        model = post
        fields = '__all__'

orm_test/views.py
from django.shortcuts import render

# Create your views here.

post/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import*
from django.views.decorators.csrf import csrf_exempt
import ast

# Create your views here.

@csrf_exempt
def main(request):

    context = {'posts': post.objects.all().order_by('-created_at')[0:10]}
    # a = ast.literal_eval(request.body)
    # print(a.get('image'))
    return render(request, 'post/main.html', context)

def create_post1(request):
    if request.method == 'GET':
        form = post_create_form()
        return render(request, 'post/create_form1.html', {'form': form})
    else:
        form = post_create_form(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
        return render(request, 'post/post_created.html')

def create_post2(request):
    if request.method == 'GET':
        return render(request, 'post/create_form2.html')
    else:

        title = request.POST.get('title')
        author = request.POST.get('author')
        content = request.POST.get('content')
        post.objects.create(title=title, author=author, content=content)
        #return render(request, 'post/post_created.html')
        return redirect('post:post_created')

def post_created(request):
    return render(request, 'post/post_created.html')

post/templates/post/create_form1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method = "POST" action = ".">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value = "추가하기">
    </form>
</body>
</html>

post/templates/post/create_form2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>
<body>
<!--
    <form method = "POST">
        <input name = "title" type = "text" placeholder="제목"><br>
        <input name = "author" type = "text" placeholder="글쓴이"><br>
        <textarea name = "content" rows = "5" placeholder="내용"></textarea><br>
        {% csrf_token %}
        <input type="submit" value = "추가하기">
    </form>
-->
<div style = "max-width:980px; margin:auto; margin-top: 100px">
    <h4 class = "mb-3">글쓰기</h4>
    <form method = "POST" class = "needs-validation">
        <div class = "row">
            <div class = "col-sm-6 mb-3">
                <label for="title" >제목</label>
                <input class = "form-control" name = "title" type = "text">
            </div>
            <div class = "col-sm-6  mb-3">
                <label for="author">글쓴이</label>
                <input class = "form-control" name = "author" type = "text">
            </div>
            <div class = "col-sm-12 mb-3">
                <label for="content">내용</label>
                <textarea class = "form-control"  name = "content" rows = "5"></textarea>
            </div>
            {% csrf_token %}
            <div class = "col-sm-12 mb-3">
                <input class = "btn btn-primary btn-lg btn-block" type="submit" value = "추가하기">
            </div>
        </div>
    </form>
</div>

</body>
</html>

post/templates/post/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <div style = "max-width: 980px; margin:auto">
        <img src="/static/dobby.jpg" style = "max-width:300px"><br>
        <a href = "{% url 'post:create_post1' %}">forms.py를 이용한 게시물 작성</a><br>
        <a href = "{% url 'post:create_post2' %}">forms.py를 이용하지 않고 게시물 작성</a>
        {% for post in posts %}
            <div style="width:100%; border:1px solid black; padding:10px; margin: 10px 0;">
                <span>
                    제목 : {{ post.title }}
                </span>
                <span>
                    글쓴이 : {{ post.author }}
                </span>
                <span>
                    작성일 : {{ post.created_at }}
                </span>
                <br>
                {% if post.image %}
                <span>
                    <img src="{{ post.image.url }}" style = "max-width:300px">
                </span>
                {% endif %}
                <br>
                <span>
                    {{ post.content | linebreaks }}
                </span>
            </div>
        {% endfor %}
    </div>


</body>
</html>

post/templates/post/post_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>post_created</title>
</head>
<body>
    <h1>
        게시물이 작성되었어요.
    </h1>
    <a href="{% url 'post:main' %}">홈</a>
</body>
</html>